version: '3.8'
services:
  diffusion_model:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0,1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: "host"
    runtime: nvidia